server:
  port: 8001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzy5639313/zyd/
          search-paths: config-repo
          username: dzy5639313@163.com
          password: dzyang25639313
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/