server:
  port: 8001
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzy5639313/zyd/    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: dzy5639313@163.com                                             # git仓库的账号
          password: dzyang25639313                                            # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   # 注册中心eurka地址